CREATE TABLE IF NOT EXISTS "historicoentrplan" (
	"ID" UUID NOT NULL UNIQUE,
	"IDESCOLA" int NOT NULL,
	"NMESCOLA" text NOT NULL,
	"IDTURMA" int NOT NULL,
	"NMTURMA" text NOT NULL,
	"MES" smallint NOT NULL,
	"ANO" smallint NOT NULL,
	"QTPLANENTR" int NOT NULL,
	"QTPLANATRASADO" int NOT NULL,
	"QTPLANNAOENTR" int NOT NULL,
	PRIMARY KEY ("ID")
);