CREATE TABLE IF NOT EXISTS `USUARIO` (
    `ID` varchar(50) NOT NULL UNIQUE,
    `NMUSUARIO` varchar(50) NOT NULL UNIQUE,
    `CARGO` varchar(30) NOT NULL,
    `DTINCLUSAO` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `DTULTATU` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `IDUSERINCLUSAO` varchar(50),
    `EMAIL` varchar(50) NOT NULL UNIQUE,
    `PASSWORD` varchar(100) NOT NULL,
    PRIMARY KEY (`ID`)
);

/

CREATE TABLE IF NOT EXISTS `ESCOLA` (
	`ID` int AUTO_INCREMENT NOT NULL UNIQUE,
	`NMESCOLA` varchar(30) NOT NULL,
	`DTINCLUSAO` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`DTULTATU` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	`IDUSERINCLUSAO` varchar(50) NOT NULL,
	PRIMARY KEY (`ID`)
);

/

CREATE TABLE IF NOT EXISTS `TURMA` (
	`ID` int AUTO_INCREMENT NOT NULL UNIQUE,
	`NMTURMA` varchar(50) NOT NULL,
	`DTINCLUSAO` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`DTULTATU` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	`IDUSERINCLUSAO` varchar(50) NOT NULL,
	`IDESCOLA` int NOT NULL,
	PRIMARY KEY (`ID`)
);

/

CREATE TABLE IF NOT EXISTS `USUARIOINSTITUICAO` (
	`ID` int AUTO_INCREMENT NOT NULL UNIQUE,
	`IDTURMA` int,
	`IDESCOLA` int NOT NULL,
	`IDUSUARIO` varchar(50) NOT NULL,
	`DTINCLUSAO` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`DTULTATU` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (`ID`)
);

/

CREATE TABLE IF NOT EXISTS `REQUISICAOMATERIAL` (
	`ID` int AUTO_INCREMENT NOT NULL UNIQUE,
	`IDMATERIAL` int NOT NULL,
	`IDUSERINCLUSAO` varchar(50) NOT NULL,
	`STATUS` varchar(20) NOT NULL,
	`DSJUSTIFICATIVA` varchar(200) NOT NULL,
	`DTUTILIZACAO` timestamp,
	`DTINCLUSAO` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`DTULTATU` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (`ID`)
);

/

CREATE TABLE IF NOT EXISTS `MATERIAL` (
	`ID` int AUTO_INCREMENT NOT NULL UNIQUE,
	`NMMATERIAL` varchar(20) NOT NULL,
	`IDUSERINCLUSAO` varchar(50) NOT NULL,
	`DTINCLUSAO` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`DTULTATU` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (`ID`)
);